name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
    - uses: actions/setup-python@v2  
      with:
        python-version: '3.x'
      
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: test
      run: make test

    - name: Run
      run: make run
    
    - name: build-container
      run: make build
